### ISSUE TITLE
UTF-8 BOM (Byte Order Mark) is incorrectly added to the serialized message bodies

### ISSUE THREAD

**Issue by jbogard** [Particular/NServiceBus.Newtonsoft.Json#53]
## Who's affected

Anyone manually deserializing NServiceBus messages using custom code.

## Symptoms

1. The first 3 bytes of the serialized message body are BOM bytes (`0xEF`,`0xBB`,`0xBF`)
1. An attempt to deserialize messages using `JsonConvert.DeserializeObject()` throws an exception "Newtonsoft.Json: Unexpected character encountered while parsing value: ?. Path '', line 0, position 0."

## Backported to

- 1.2.1 https://github.com/Particular/NServiceBus.Newtonsoft.Json/pull/56

## Original issue

The BOM for UTF-8 is currently added to outgoing messages:

```c#
_messageSession.Send(new SaySomethingCommand {Message = "Hello World"});
```

Becomes:

```json
{"Message":"Hello World"}
```

However, looking at the bytes, the BOM is added:

```
EFBBBF7B224D657373616765223A2248656C6C6F20576F726C64227D
```

Which, decoding, looks like:

```
ï»¿{"Message":"Hello World"}
```

If you try to manually deserialize through JSON.NET, say for an integration scenario, Azure Functions, Web Jobs etc:

```c#
var body = Encoding.UTF8.GetString(message.Body);
var command = JsonConvert.DeserializeObject<SaySomethingCommand>(body);
```

This will fail with the message:

```
Newtonsoft.Json: Unexpected character encountered while parsing value: ?. Path '', line 0, position 0.
```

Per the [RFC](https://tools.ietf.org/html/rfc7159#section-8.1):

> Implementations MUST NOT add a byte order mark to the beginning of a JSON text.

The JSON in the message, because it includes a BOM, isn't actually valid JSON.

**Comment by jbogard** [comment]
I should mention that even though the content-type header was added per https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/19, you can't use it with Functions/Web Jobs because the BOM causes the JSON.NET serializer to blow up. You can't use the raw bytes, either, without first stripping out the BOM. Instead, you have to use a string, which removes the BOM, then deserialize from there.

**Comment by jbogard** [comment]
To configure NServiceBus to emit valid JSON:

```c#
var serialization = endpointConfiguration.UseSerialization<NewtonsoftSerializer>();
serialization.WriterCreator(s =>
{
    var streamWriter = new StreamWriter(s, new UTF8Encoding(false));
    return new JsonTextWriter(streamWriter);
});
```

**Comment by bording** [comment]
After further analysis, we realized that this could introduce a wire compatibility breaking change in some scenarios. The could occur due to the fact that we have APIs that allow people to change the default encoding.

We have decided not to release these hotfixes, and instead suggest that if you are in a scenario where you are impacted by the serializer emitting a Byte Order Mark, you should use the APIs we provide to customize the encoding so that it is not emitted.

Examples of how to do this can be seen in our documentation for both the [NServiceBus.Newtonsoft.Json package](https://docs.particular.net/nservicebus/serialization/newtonsoft#usage-custom-writer) and the [built-in JSON serializer](https://docs.particular.net/nservicebus/serialization/json?#customization-customizing-encoding) used in NServiceBus 6.

**Comment by jbogard** [comment]
How does this affect folks that change the encoding? Do you have a repro?

**Comment by bording** [comment]
> How does this affect folks that change the encoding?

The problem is related to how `StreamReader` has byte order mark detection enabled by default and the fact that it can hide configuration mismatches.

1. `Endpoint1` is using default encoding (UTF8 with BOM) 
2. `Endpoint2` is using customized encoding (UTF32 with BOM)
3. `Endpoint1` sends a message to `Endpoint2`
4. Despite having mismatched encoding settings, `Endpoint2` successfully deserializes the message because the `StreamReader` detects the BOM and decodes the message properly.

If we had released these patches, then this would instead be:

1. `Endpoint1`  is using default encoding (UTF8 w/o BOM)  
2. `Endpoint2` is using customized encoding (UTF32 with BOM)
3. `Endpoint1` sends a message to `Endpoint2`
4. `Endpoint2` fails to deserialize the message because it has no BOM, so the `StreamReader` falls back to the configured encoding, which is not the same as the encoding used by `Endpoint1`.

While this can be considered an edge case, the fact that it was possible for these patches to cause a break in a previously working system, and that we already offer APIs to remove the BOM for scenarios where it causes a problem, lead us to decide not to make a change here.

**Comment by ramonsmits** [comment]
Reading this, we should not add a BOM by default IMHO. If this is breaking compatibility we should have it an explicit opt-in by creating a new major version.

**Comment by bording** [comment]
@ramonsmits I disagree, because this a wire compat concern.

**Comment by jbogard** [comment]
Just as an FYI, the BOM present breaks all sorts of other things too - visualizers, debuggers, tracing tools...to fix this you'd have to fix wire compat too.

**Comment by ramonsmits** [comment]
A BOM is meant for files, not for streams. The type of streams and its encoding should be part of the header or if not present a default should be assumed.

In case of JSON the message body should not have a BOM and if really needed the character set could be appended to the content type like `; charset=utf-8`. This I already mentioned in https://github.com/Particular/NServiceBus/issues/4211 and https://github.com/Particular/NServiceBus/issues/3318

**Comment by SimonCropp** [comment]
@jbogard @seanfarmar https://github.com/NServiceBusExtensions/NServiceBus.Json

**Comment by SeanFeldman** [comment]
Thank you, @SimonCropp

**Comment by jgauffin** [comment]
This is indeed strange behavior. It's unexpected. 

You could have transported the BOM within a header, or the encoding itself. HTTP does it by adding `;charset=utf8` to the content type header.

**Comment by ramonsmits** [comment]
@jgauffin Yes, this was a design issue but it needs to remain backwardscompatible. As mentioned there are ways to avoid the Byte Order Mark (BOM) characters `ï»¿`.

https://docs.particular.net/nservicebus/serialization/json?#customization-customizing-encoding
